name: "publish npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: publish
        run: npm publish --access public
        working-directory: ${{ github.workspace }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISHGITHUB }}
